### ISSUE TITLE
The user's password checker

### ISSUE THREAD

**Issue by umutaev** [wantit-ml/wantit-backend#23]
Please add the user's password checker.  It will be more optimized than if I do it by myself. You simply should add another parameter (user_password: str) for function create_session and check, if this password correct or not. Remember, all hashing logic is in your code. And the same thing for verifying sessions.
https://github.com/wantit-ml/wantit-backend/blob/fb9c785a11f392e4f03dbb054f60ab9e8c97dbd2/app/db/user.py#L78

**Comment by Fodro** [comment]
Completed
